# Base the image on Rocky Linux (Red hat compatible)
FROM rockylinux:9

ARG REPOSITORY_URI
ARG GITHUB_BRANCH

USER root

RUN useradd -m -r boa

RUN yum install -y epel-release-9-10.el9

RUN yum install --allowerasing -y \
    python3-3.9.25-3.el9_7.1 \
    python3-pip-21.3.1-1.el9 \
    python3-tkinter-3.9.25-3.el9_7.1 \
    python3-devel-3.9.25-3.el9_7.1 \
    make-1:4.3-8.el9 \
    which-2.21-30.el9_6 \
    p7zip-16.02-31.el9 \
    unzip-6.0-59.el9 \
    less-590-6.el9 \
    cronie-1.5.7-15.el9 \
    libcurl-7.76.1-35.el9_7.3 \
    libcurl-devel-7.76.1-35.el9_7.3 \
    libpq-devel-13.23-1.el9_7 \
    postgresql-13.23-2.el9_7 \
    podman-docker-6:5.6.0-14.el9_7 \
    procps-ng-3.3.17-14.el9 \
    glibc-langpack-en-2.34-231.el9_7.10 \
    redhat-rpm-config-210-1.el9

RUN yum install -y \
    ruby-3.0.7-165.el9_5 \
    rubygem-bundler-2.2.33-165.el9_5 \
    ruby-devel-3.0.7-165.el9_5

RUN yum install -y git-2.47.3-1.el9_6

RUN pip3 install wheel
    
# Create folders for BOA
RUN mkdir /log
RUN mkdir /scripts
RUN mkdir /resources_path
RUN mkdir /schemas
RUN mkdir /datamodel
RUN mkdir /rboa_archive
RUN mkdir /metrics
RUN mkdir /metrics_to_publish
RUN mkdir /eboa

# Change ownership to the boa user
RUN chown -R boa /log /scripts /resources_path /schemas /datamodel /rboa_archive /metrics /metrics_to_publish /eboa

# Create a shared folder for python packages
RUN mkdir /usr/local/python-packages
RUN chown -R boa:boa /usr/local/python-packages
ENV PYTHONPATH=/usr/local/python-packages

# Add path to the binaries installed by pip to PATH
ENV PATH="/usr/local/python-packages/bin:${PATH}"

# Add path to the binaries installed by ruby in the home of the boa user to PATH
ENV PATH="/home/boa/bin:${PATH}"

USER boa

# Install EBOA packages
RUN git clone --branch ${GITHUB_BRANCH} ${REPOSITORY_URI}

RUN pip3 install --use-pep517 --target=/usr/local/python-packages "/eboa/src[tests]"

# Copy EBOA configurations
RUN cp /eboa/src/config/* /resources_path

# Copy EBOA scripts
RUN cp /eboa/src/scripts/* /scripts

# Copy EBOA ingestion chain
RUN cp /eboa/src/eboa/triggering/eboa_triggering.py /scripts/eboa_triggering.py
RUN cp /eboa/src/eboa/ingestion/eboa_ingestion.py /scripts/eboa_ingestion.py

# Copy EBOA data models
RUN cp /eboa/src/datamodel/eboa_data_model.sql /datamodel
RUN cp /eboa/src/datamodel/sboa_data_model.sql /datamodel
RUN cp /eboa/src/datamodel/uboa_data_model.sql /datamodel

# Copy EBOA schemas
RUN cp /eboa/src/schemas/* /schemas

# Copy RBOA reporting chain
RUN cp /eboa/src/rboa/triggering/rboa_triggering.py /scripts/rboa_triggering.py
RUN cp /eboa/src/rboa/reporting/rboa_reporting.py /scripts/rboa_reporting.py

# Copy SBOA scheduler chain
RUN cp /eboa/src/sboa/scheduler/boa_scheduler.py /scripts/boa_scheduler.py
RUN cp /eboa/src/sboa/scheduler/boa_execute_triggering.py /scripts/boa_execute_triggering.py

# Environment Variables for BOA
ENV EBOA_RESOURCES_PATH /resources_path
ENV EBOA_LOG_PATH /log
ENV EBOA_SCHEMAS_PATH /schemas
ENV LC_ALL en_US.utf-8
ENV LANG en_US.utf-8
ENV PATH="${PATH}:/scripts"
ENV RBOA_ARCHIVE_PATH="/rboa_archive"

# Add path to the scripts installed by pip in the home of the boa user to PATH
ENV PATH="${PATH}:/usr/local/python-packages/bin"

# expose port
EXPOSE 5001

# Copy the environment variables to a file for later use of cron
RUN declare -p | grep -Ev 'BASHOPTS|BASH_VERSINFO|EUID|PPID|SHELLOPTS|UID' > /resources_path/container.env

CMD ["/bin/bash", "-c", "/scripts/start_eboa.sh"]
