# Github actions for testing EBOA
name: "EBOA testing"
on:
  push:
    branches:
      - "*"

jobs:
  # Integration Test
  tests:
    name: "Integration Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up environment"
        run: GITHUB_BRANCH=${{ github.ref }} REPOSITORY_URI=${{ github.repositoryUrl }} docker compose -f compose_eboa_github_dev.yml up -d --wait
      - name: "Test EBOA"
        run: docker exec eboa bash -c "/scripts/initialize_eboa_ddbb.sh; cd /eboa/src; py.test -vv tests/ eboa/ingestions"
